version: 3
dependencies:
- type: git
  manifest_updates:
    filters:
    - name: .* # everything else
      enabled: true
  settings:
    # Assign to maintainers by default
    # gitlab_assignee_ids:
      ## maintainers
      # - 597578  # @WarheadsSE (jplum)
      # - 5727219 # @mnielsen (mnielsen)
      ## trainee maintainers
      # - 13376698 # clemensbeck
      # - 4849     # balasankarc (balu)
    gitlab_labels:
      - dependencies.io
      - group::distribution::deploy
      - group::distribution
      - section::core platform
      - devops::systems
      - type::maintenance
      - maintenance::dependency
      - workflow::ready for review
    gitlab_remove_source_branch: true
    commit_message_template: |-
      {{.SubjectAndBody}}

      Changelog: changed
    remotes:
      # Registry chart / container
      https://gitlab.com/gitlab-org/container-registry.git:
        replace_in_files:
        - filename: doc/charts/registry/index.md
          pattern: "tag: 'v(\\S+)'"
          range: '>= 2.x.x'
          prereleases: true
        - filename: doc/charts/registry/index.md
          pattern: '`v(\d+\.\d+\.\d+-gitlab)`'
          range: '>= 2.x.x'
          prereleases: true
        - filename: charts/registry/Chart.yaml
          pattern: "appVersion: 'v(\\S+)'"
          range: '>= 2.x.x'
          prereleases: true
        - filename: charts/registry/values.yaml
          pattern: "tag: 'v(\\S+)'"
          range: '>= 2.x.x'
          prereleases: true
      # GitLab Exporter
      https://gitlab.com/gitlab-org/gitlab-exporter.git:
        replace_in_files:
        - filename: charts/gitlab/charts/gitlab-exporter/Chart.yaml
          pattern: 'appVersion: (\S+)'
      # GitLab Runner Chart
      https://gitlab.com/gitlab-org/charts/gitlab-runner.git:
        replace_in_files:
        - filename: requirements.yaml
          pattern: 'name: gitlab-runner\n  version: (\S+)'
      # GitLab QA Gem
      https://gitlab.com/gitlab-org/gitlab-qa.git:
        replace_in_files:
        - filename: .gitlab-ci.yml
          pattern: 'GITLAB_QA_VERSION: "(\S+)"'
      # cert-manager subchart
      https://github.com/cert-manager/cert-manager.git:
        replace_in_files:
        - filename: requirements.yaml
          pattern: 'name: cert-manager\n  version: (\S+)'
          range: '< 1.13.0'
